### ISSUE TITLE
Add please some features

### ISSUE THREAD

**Issue by NeoFolia** [getplusm/ProtectionsBlocks#2]
1. I would like a configuration to disable particles when installing or breaking regional blocks.
2. I would like to see auto flags that can be set for each block, for example, for a golden block (region), I want to disable the destruction of blocks by creepers or withers.

**Comment by NeoFolia** [comment]
I would like to make a region from a netherite block that would have flags so that it is impossible to explode the blocks inside it with dynamite, wither, crystals and creepers. But this region needs money to exist.

**Comment by NeoFolia** [comment]
Now I can’t do this in any way :( since your plugin does not have automatic explosion protection flags in the region

**Comment by getplusm** [comment]
The function of the particles will be added, but everything else is already in the plugin
