### ISSUE TITLE
Make a total block region limit

### ISSUE THREAD

**Issue by NeoFolia** [getplusm/ProtectionsBlocks#4]
Make a total block region limit

Players create a bunch of private blocks and place them in turns, thus they can have more than 2+ privates, but I would like to make it possible to have only 1 region.

**Comment by NeoFolia** [comment]
You have a limit for each block, but I would like to see the total limit for all regions, let’s say only 1 block could be given to a player.

**Comment by getplusm** [comment]
Now you can set global limit on config.yml
